# Generated by Django 5.0.6 on 2024-06-20 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatgroup_groupmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="group",
        ),
        migrations.RemoveField(
            model_name="chatnotification",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="chatnotification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatGroup",
        ),
        migrations.DeleteModel(
            name="ChatNotification",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
        migrations.DeleteModel(
            name="UserProfileModel",
        ),
    ]
