# Generated by Django 5.0.6 on 2024-06-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatgroup_chatnotification_groupmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
