# Generated by Django 5.0.6 on 2024-06-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_chatadmin_message_messagemedia_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
