# Generated by Django 5.0.6 on 2024-06-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_chatmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_type', 'title')},
        ),
    ]
