# Generated by Django 5.0.6 on 2024-05-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_preregistration_remove_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='code',
            field=models.IntegerField(max_length=8),
        ),
    ]
