# Generated by Django 5.0.6 on 2024-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_preregistration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
