# Generated by Django 5.0.6 on 2024-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_preregistration_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistration',
            old_name='code',
            new_name='code_e',
        ),
    ]
