# Generated by Django 5.0.6 on 2024-06-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_code_preregistration_code_e'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregistration',
            old_name='code_e',
            new_name='code',
        ),
    ]
